<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Modules.Common.Features\Modules.Common.Features.csproj" />
    <ProjectReference Include="..\Modules.WorkLogs.Domains\Modules.WorkLogs.Domains.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
  </ItemGroup>

</Project>
